version: "3"
services:
  node-app:
    container_name: "testnodeapp"
    build:
      context: .
      target: development

    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=DEVELOPER
    env_file:
      - .env