name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs1:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
          run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"

jobs2:
    build2:
        runs-on: ubuntu-latest

        steps:
            - name: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
              run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
jobs3:
    build3:
        runs-on: ubuntu-latest

        steps:
            - name: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
              run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
    needs: [build2]

jobs4:
    build4:
        runs-on: ubuntu-latest

        steps:
            - name: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
              run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
    needs: [build3, build1]
