name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print job and workflow name
        run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: print job and workflow name
        run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"

  build3:
    needs: build2
    runs-on: ubuntu-latest
    steps:
      - name: print job and workflow name
        run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"

  build4:
    needs: [build3, build]
    runs-on: ubuntu-latest
    steps:
      - name: print job and workflow name
        run: echo "From job name: ${{ github.job }} and workflow name: ${{ github.workflow }}"
